[package]
name = "github-webhook"
version = "0.1.0+v6.8.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
github-webhook-type-generator = { path = "../type-generator" }
anyhow = "1.0.68"
reqwest = { version = "0.11.13", features = ["blocking"] }

[dependencies]
serde = "1.0.151"
