[package]
name = "github-webhook-type-generator"
version.workspace = true
rust-version.workspace = true
edition = "2021"

description = "GitHub webhook payload type generator for Rust"
repository.workspace = true
authors.workspace = true
license = "MIT"

[features]
default = ["serde"]
serde = []

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
structopt = "0.3.26"
swc_common = { version = "0.32.1", features = ["tty-emitter"]}
swc_ecma_ast = "0.109.1"
swc_ecma_parser = "0.140.0"
once_cell = "1.18.0"
