[package]
name = "github-webhook-type-generator"
version.workspace = true
rust-version.workspace = true
edition = "2021"

description = "GitHub webhook payload type generator for Rust"
repository.workspace = true
authors.workspace = true
license = "MIT"

[features]
default = ["serde"]
serde = []

[dependencies]
proc-macro2 = "1.0.60"
quote = "1.0.28"
structopt = "0.3.26"
swc_common = { version = "0.31.12", features = ["tty-emitter"]}
swc_ecma_ast = "0.106.0"
swc_ecma_parser = "0.136.0"
once_cell = "1.18.0"
