[package]
name = "github-webhook-type-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
structopt = "0.3.26"
swc_common = { version = "0.29.22", features = ["tty-emitter"]}
swc_ecma_ast = "0.95.6"
swc_ecma_parser = "0.123.9"
