[package]
name = "github-webhook-dts-downloader"
version = "0.1.0"
edition = "2021"

description = "GitHub webhook payload type def downloader for Rust"
repository.workspace = true
authors.workspace = true
license = "MIT"

[dependencies]
github-webhook-type-generator.workspace = true
anyhow = "1.0.70"
reqwest = { version = "0.11.18", features = ["blocking"] }
